"""hash api keys, add review approval workflow

Revision ID: 26b4207992da
Revises: dfc937135447
Create Date: 2026-08-27 03:42:31.741184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b4207992da'
down_revision = 'dfc937135447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_versions', sa.Column('reviewed_by', sa.String(), nullable=True))
    op.add_column('skill_versions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('api_key_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('api_key_revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_users_api_key', table_name='users')
    op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=True)
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    op.create_index('ix_users_api_key', 'users', ['api_key'], unique=1)
    op.drop_column('users', 'api_key_revoked_at')
    op.drop_column('users', 'api_key_hash')
    op.drop_column('skill_versions', 'reviewed_at')
    op.drop_column('skill_versions', 'reviewed_by')
    # ### end Alembic commands ###
